## 设置启动的配置
spring:
  profiles:
    active: dev
    include: common
  #配置mongodb
  application:
    name: spring-boot-mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin
      username: root
      password: root
  #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
  messages:
    basename: i18n/message
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 5
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    hibernate:
      ddl-auto: update
      ## Spring Boot集成JPA的Column注解命名字段无效的问题
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ## 设置字段格式化
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  ## 定义日期的格式,规范，json的赋值规范等
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    joda-date-time-format: yyyy-MM-dd HH:mm:ss

# 外网请求的ip
api.address: http://127.0.0.1:9090/
api.recylerview: https://gank.io/